name: ColorChat
version: 1.0-indev
api: [4.0.0, 4.2.2, 4.2.3, 4.2.4]
author: ["DctxGamesMC", "ItzToxicGG"]
main: ToxicGG\ColorChat\Main
description: A Plugin that allows you to change your chat color
